### ISSUE TITLE
Add code typography styles

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/styles#148]
Consider both inline and code blocks.

**Comment by helrond** [comment]
@HaSistrunk is something above and beyond the default browser styling for `code` and `pre` tags expected here, and/or is there an example I can look at?

**Comment by HaSistrunk** [comment]
> @HaSistrunk is something above and beyond the default browser styling for `code` and `pre` tags expected here, and/or is there an example I can look at?

Yes. On the Docs Site that uses code more frequently, we found that the default styles were tough to distinguish from regular text and not doing any favors for our technical documentation, so we implemented some [custom styles](https://github.com/RockefellerArchiveCenter/docs-build/pull/133). You can check out what those look like in examples [in the docs site guide](https://docs.rockarch.org/docs-guide/edit-content) and [in the API docs](https://docs.rockarch.org/argo-docs/use-api).

However, those Docs site styles rely on [Rouge](https://rouge.jneen.net/), the Ruby code highlighter that is built into Jekyll and allows you to specify the code language. I'm not sure if we need all that, but I thought it would be worth researching a bit to see if there were solutions that would improve the readability of code in our docs.

It could be that the custom code styles just stay locally in the Docs Site, and we don't include all of that in the Style Library. I welcome your thoughts!

**Comment by HaSistrunk** [comment]
Code styles were added locally to the Docs Site and Bits & Bytes using SCSS rouge syntax highlighter styles that work with Jeykyll. At this time, there is no need to incorporate these into the Style Library.
