### ISSUE TITLE
Update Twitter logo for social icons

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/styles#178]
## Is your feature request related to a problem? Please describe.
Twitter logo has changed.

## Describe the solution you'd like
Update Twitter social media icon to the new X logo.

**Comment by Hemanthhari2000** [comment]
Hi, I would like to work on this under Hacktoberfest and can you please assign me this?. It would be great if you can tag this under hacktoberfest if possible.

**Comment by HaSistrunk** [comment]
> Hi, I would like to work on this under Hacktoberfest and can you please assign me this?. It would be great if you can tag this under hacktoberfest if possible.

Hi @Hemanthhari2000! Thanks for your interest in contributing, but at this time we're keeping the work internal in our organization. Much appreciated~

**Comment by HaSistrunk** [comment]
Also noting that Flickr is included in our social media component, and not LinkedIn. We should evaluate all of these and make sure they are in line with our [content strategy](https://docs.rockarch.org/r-e-content-strategy).

**Comment by HaSistrunk** [comment]
After consultation with social media team, decided to remove Flickr and Twitter, and add LinkedIn
