### ISSUE TITLE
Remove `select__label` and `select__control` classes from Select component

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/styles#199]
## Describe the bug
The `select__label` and `select__control` classes which are included in the Select component do not have corresponding styles, so they can be removed.

## Expected behavior
Classes should either have styles associated with them, or should not exist.

## Impact on your work
Minor bug, but good to get resolved before wider implementation of the RAC style library.

**Comment by HaSistrunk** [comment]
Do you have an opinion on if we should make our select component look more like the ones in DIMES? That is a custom components that we [decided not to use](https://github.com/RockefellerArchiveCenter/styles/pull/80) in terms of HTML structure, but we could make them look like this (although we can't style the select options): 
<img width="213" alt="image" src="https://github.com/RockefellerArchiveCenter/styles/assets/15254041/17a119ad-8927-43f6-acf8-69c66522436f">

I don't see/recall why we just went with an unstyled select in the Style Library.

**Comment by helrond** [comment]
I don't recall either - it could be that unstyled options look weird in combination with the other styling. I wouldn't be opposed to some experimentation though.
