### ISSUE TITLE
Improve compile defaults

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/styles#7]
## Is your feature request related to a problem? Please describe.
Ideally the compiled CSS should be compressed. Vendor prefixes should also be applied.

## Describe the solution you'd like
Add arguments and other configs as necessary to optimize compilation of CSS. [This post](https://stackoverflow.com/questions/54435999/use-sass-from-command-line-and-autoprefixer-for-bootstrap-4-x) is helpful; it may be necessary to use PostCSS or Less: `sass stylesheets/main.scss dist/main.css --style=compressed && postcss dist/main.css --replace --use autoprefixer`

**Comment by HaSistrunk** [comment]
A useful resource on PostCSS: [https://www.sitepoint.com/postcss-sass-configurable-alternative/](https://www.sitepoint.com/postcss-sass-configurable-alternative/)
