### ISSUE TITLE
Add styles for minimap component

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/styles#90]
Use Story from issue #89.

**Comment by helrond** [comment]
Noting one thing I inadvertently discovered - having a flexible width on this component but a fixed width on the boxes within it wreaks havoc with the calculations of the number of boxes that fit in the component, so I think we should probably set a fixed width on this component that's tied to an even multiple of the squares OR we should make the squares responsive as well as the boxes. LMK if that doesn't make sense!
